import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Provider } from "react-redux";
import { ReduxProvier } from "@/redux/provider";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="heading">
          <h1>BMI Calculator</h1>
        </div>
        <div className="child">
          <ReduxProvier className="child">{children}</ReduxProvier>
        </div>
      </body>
    </html>
  );
}
